
CREATE DATABASE pis;

CREATE USER user01 IDENTIFIED BY 'user1234';

CREATE USER pis01 IDENTIFIED BY 'pis1234';

CREATE TABLE USER (
    USER_ID MEDIUMINT NOT NULL,
    USER_NAME VARCHAR(20),
    EMAIL VARCHAR(50),
    BIRTH_DATE DATE,
    CONTACT_NUMBER VARCHAR(20)
);

GRANT ALL ON PIS.* TO 'pis01'@'%';

INSERT INTO USER (USER_ID, USER_NAME, EMAIL, BIRTH_DATE, CONTACT_NUMBER) VALUES (1, 'aaa', 'aaa@gmail.com', '1980-01-01', 09271234567);

INSERT INTO USER (USER_ID, USER_NAME, EMAIL, BIRTH_DATE, CONTACT_NUMBER) VALUES (1, :userName, :email, :birthDate, :contactNumber);